
package com.shentian.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * <h2>中商网络数码真伪查询服务</h2>
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OutDigitCodeService", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", wsdlLocation = "file:/F:/software/Test/NewWSDLFile.wsdl")
public class OutDigitCodeService
    extends Service
{

    private final static URL OUTDIGITCODESERVICE_WSDL_LOCATION;
    private final static WebServiceException OUTDIGITCODESERVICE_EXCEPTION;
    private final static QName OUTDIGITCODESERVICE_QNAME = new QName("http://fw.yesno.com.cn/CCNCommonService", "OutDigitCodeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/F:/software/Test/NewWSDLFile.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OUTDIGITCODESERVICE_WSDL_LOCATION = url;
        OUTDIGITCODESERVICE_EXCEPTION = e;
    }

    public OutDigitCodeService() {
        super(__getWsdlLocation(), OUTDIGITCODESERVICE_QNAME);
    }

    public OutDigitCodeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), OUTDIGITCODESERVICE_QNAME, features);
    }

    public OutDigitCodeService(URL wsdlLocation) {
        super(wsdlLocation, OUTDIGITCODESERVICE_QNAME);
    }

    public OutDigitCodeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OUTDIGITCODESERVICE_QNAME, features);
    }

    public OutDigitCodeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OutDigitCodeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OutDigitCodeServiceSoap
     */
    @WebEndpoint(name = "OutDigitCodeServiceSoap")
    public OutDigitCodeServiceSoap getOutDigitCodeServiceSoap() {
        return super.getPort(new QName("http://fw.yesno.com.cn/CCNCommonService", "OutDigitCodeServiceSoap"), OutDigitCodeServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OutDigitCodeServiceSoap
     */
    @WebEndpoint(name = "OutDigitCodeServiceSoap")
    public OutDigitCodeServiceSoap getOutDigitCodeServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://fw.yesno.com.cn/CCNCommonService", "OutDigitCodeServiceSoap"), OutDigitCodeServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OUTDIGITCODESERVICE_EXCEPTION!= null) {
            throw OUTDIGITCODESERVICE_EXCEPTION;
        }
        return OUTDIGITCODESERVICE_WSDL_LOCATION;
    }

}
