
package com.shentian.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OutDigitCodeServiceSoap", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OutDigitCodeServiceSoap {


    /**
     * CCN防伪信息查询接口,详情请参见<<中商通用服务接口及数据更新组件设计文档>>
     * 
     * @param mima
     * @param code
     * @param ip
     * @param getCodeIsTrueResult
     * @param reply
     * @param directoryName
     */
    @WebMethod(operationName = "Get_CodeIsTrue", action = "http://fw.yesno.com.cn/CCNCommonService/Get_CodeIsTrue")
    @RequestWrapper(localName = "Get_CodeIsTrue", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", className = "com.shentian.client.GetCodeIsTrue")
    @ResponseWrapper(localName = "Get_CodeIsTrueResponse", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", className = "com.shentian.client.GetCodeIsTrueResponse")
    public void getCodeIsTrue(
        @WebParam(name = "directoryName", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String directoryName,
        @WebParam(name = "mima", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String mima,
        @WebParam(name = "code", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String code,
        @WebParam(name = "ip", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String ip,
        @WebParam(name = "Get_CodeIsTrueResult", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<Boolean> getCodeIsTrueResult,
        @WebParam(name = "reply", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<String> reply);

    /**
     * CCN防伪信息查询接口
     * 
     * @param queryCodeInfoResult
     * @param mima
     * @param code
     * @param systemState
     * @param ip
     * @param reply
     * @param directoryName
     */
    @WebMethod(operationName = "QueryCodeInfo", action = "http://fw.yesno.com.cn/CCNCommonService/QueryCodeInfo")
    @RequestWrapper(localName = "QueryCodeInfo", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", className = "com.shentian.client.QueryCodeInfo")
    @ResponseWrapper(localName = "QueryCodeInfoResponse", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", className = "com.shentian.client.QueryCodeInfoResponse")
    public void queryCodeInfo(
        @WebParam(name = "directoryName", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String directoryName,
        @WebParam(name = "mima", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String mima,
        @WebParam(name = "code", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String code,
        @WebParam(name = "ip", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String ip,
        @WebParam(name = "QueryCodeInfoResult", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<com.shentian.client.QueryCodeInfoResponse.QueryCodeInfoResult> queryCodeInfoResult,
        @WebParam(name = "reply", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<String> reply,
        @WebParam(name = "systemState", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<String> systemState);

    /**
     * CCN防伪信息查询接口,详情请参见<<中商通用服务接口及数据更新组件设计文档>>
     * 
     * @param parameters
     * @return
     *     returns com.shentian.client.QueryCodeTrueOrFalseGlobalResponse
     */
    @WebMethod(operationName = "Get_CodeIsTrueGlobal", action = "http://fw.yesno.com.cn/CCNCommonService/QueryCodeTrueOrFalseGlobal")
    @WebResult(name = "QueryCodeTrueOrFalseGlobalResponse", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public QueryCodeTrueOrFalseGlobalResponse getCodeIsTrueGlobal(
        @WebParam(name = "QueryCodeTrueOrFalseGlobal", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", partName = "parameters")
        QueryCodeTrueOrFalseGlobal parameters);

    /**
     * CCN防伪信息查询接口,详情请参见<<中商通用服务接口及数据更新组件设计文档>>
     * 
     * @param parameters
     * @return
     *     returns com.shentian.client.QueryCodeTrueOrFalseGlobalForOtherResponse
     */
    @WebMethod(operationName = "Get_CodeIsTrueGlobalForOther", action = "http://fw.yesno.com.cn/CCNCommonService/QueryCodeTrueOrFalseGlobalForOther")
    @WebResult(name = "QueryCodeTrueOrFalseGlobalForOtherResponse", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public QueryCodeTrueOrFalseGlobalForOtherResponse getCodeIsTrueGlobalForOther(
        @WebParam(name = "QueryCodeTrueOrFalseGlobalForOther", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", partName = "parameters")
        QueryCodeTrueOrFalseGlobalForOther parameters);

    /**
     * CCN防伪信息查询接口
     * 
     * @param parameters
     * @return
     *     returns com.shentian.client.QueryCodeInfoGlobalResponse
     */
    @WebMethod(operationName = "Get_CodeIsTrueGlobal", action = "http://fw.yesno.com.cn/CCNCommonService/QueryCodeInfoGlobal")
    @WebResult(name = "QueryCodeInfoGlobalResponse", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public QueryCodeInfoGlobalResponse getCodeIsTrueGlobal(
        @WebParam(name = "QueryCodeInfoGlobal", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", partName = "parameters")
        QueryCodeInfoGlobal parameters);

    /**
     * CCN防伪信息查询接口,详情请参见<<中商通用服务接口及数据更新组件设计文档>>
     * 
     * @param mima
     * @param code
     * @param called
     * @param systemState
     * @param src
     * @param ip
     * @param language
     * @param reply
     * @param directoryName
     * @param getCodeIsTrue2Result
     */
    @WebMethod(operationName = "Get_CodeIsTrue2", action = "http://fw.yesno.com.cn/CCNCommonService/Get_CodeIsTrue2")
    @RequestWrapper(localName = "Get_CodeIsTrue2", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", className = "com.shentian.client.GetCodeIsTrue2")
    @ResponseWrapper(localName = "Get_CodeIsTrue2Response", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", className = "com.shentian.client.GetCodeIsTrue2Response")
    public void getCodeIsTrue2(
        @WebParam(name = "directoryName", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String directoryName,
        @WebParam(name = "mima", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String mima,
        @WebParam(name = "code", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String code,
        @WebParam(name = "ip", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String ip,
        @WebParam(name = "language", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        Language language,
        @WebParam(name = "called", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String called,
        @WebParam(name = "src", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String src,
        @WebParam(name = "Get_CodeIsTrue2Result", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<String> getCodeIsTrue2Result,
        @WebParam(name = "reply", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<String> reply,
        @WebParam(name = "systemState", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<String> systemState);

    /**
     * CCN防伪信息查询接口,详情请参见<<中商通用服务接口及数据更新组件设计文档>>
     * 
     * @param factoryCode
     * @param request
     * @param channletType
     * @param called
     * @param ip
     * @param language
     * @param queryCount
     * @param productInfo
     * @param getDigitCodeInfoResult
     * @param password
     * @param digitCode
     * @param systemState
     * @param firstQueryDate
     * @param reply
     */
    @WebMethod(operationName = "GetDigitCodeInfo", action = "http://fw.yesno.com.cn/CCNCommonService/GetDigitCodeInfo")
    @RequestWrapper(localName = "GetDigitCodeInfo", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", className = "com.shentian.client.GetDigitCodeInfo")
    @ResponseWrapper(localName = "GetDigitCodeInfoResponse", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", className = "com.shentian.client.GetDigitCodeInfoResponse")
    public void getDigitCodeInfo(
        @WebParam(name = "factoryCode", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String factoryCode,
        @WebParam(name = "password", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String password,
        @WebParam(name = "digitCode", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String digitCode,
        @WebParam(name = "IP", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String ip,
        @WebParam(name = "channletType", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String channletType,
        @WebParam(name = "language", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        int language,
        @WebParam(name = "called", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String called,
        @WebParam(name = "request", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        ArrayOfString request,
        @WebParam(name = "GetDigitCodeInfoResult", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<Boolean> getDigitCodeInfoResult,
        @WebParam(name = "systemState", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<String> systemState,
        @WebParam(name = "reply", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<String> reply,
        @WebParam(name = "firstQueryDate", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<String> firstQueryDate,
        @WebParam(name = "queryCount", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<String> queryCount,
        @WebParam(name = "productInfo", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<ArrayOfString> productInfo);

    /**
     * CCN防伪信息查询接口,详情请参见<<中商通用服务接口及数据更新组件设计文档>>
     * 
     * @param mima
     * @param code
     * @param getCodeIsTrueGlobal2Result
     * @param ip
     * @param language
     * @param reply
     * @param directoryName
     */
    @WebMethod(operationName = "Get_CodeIsTrueGlobal2", action = "http://fw.yesno.com.cn/CCNCommonService/Get_CodeIsTrueGlobal2")
    @RequestWrapper(localName = "Get_CodeIsTrueGlobal2", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", className = "com.shentian.client.GetCodeIsTrueGlobal2")
    @ResponseWrapper(localName = "Get_CodeIsTrueGlobal2Response", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", className = "com.shentian.client.GetCodeIsTrueGlobal2Response")
    public void getCodeIsTrueGlobal2(
        @WebParam(name = "directoryName", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String directoryName,
        @WebParam(name = "mima", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String mima,
        @WebParam(name = "code", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String code,
        @WebParam(name = "ip", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String ip,
        @WebParam(name = "language", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        int language,
        @WebParam(name = "Get_CodeIsTrueGlobal2Result", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<Boolean> getCodeIsTrueGlobal2Result,
        @WebParam(name = "reply", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<String> reply);

    /**
     * 数码验证+其他信息获取和校验接口
     * 
     * @param systemState
     * @param acCode
     * @param ip
     * @param userPwd
     * @param channel
     * @param language
     * @param getAcCodeInfoInterfaceResult
     * @param reply
     * @param userID
     */
    @WebMethod(operationName = "Get_AcCodeInfoInterface", action = "http://fw.yesno.com.cn/CCNCommonService/Get_AcCodeInfoInterface")
    @RequestWrapper(localName = "Get_AcCodeInfoInterface", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", className = "com.shentian.client.GetAcCodeInfoInterface")
    @ResponseWrapper(localName = "Get_AcCodeInfoInterfaceResponse", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", className = "com.shentian.client.GetAcCodeInfoInterfaceResponse")
    public void getAcCodeInfoInterface(
        @WebParam(name = "userID", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String userID,
        @WebParam(name = "userPwd", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String userPwd,
        @WebParam(name = "ip", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String ip,
        @WebParam(name = "acCode", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String acCode,
        @WebParam(name = "language", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String language,
        @WebParam(name = "channel", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String channel,
        @WebParam(name = "Get_AcCodeInfoInterfaceResult", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<Boolean> getAcCodeInfoInterfaceResult,
        @WebParam(name = "reply", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<String> reply,
        @WebParam(name = "systemState", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<String> systemState);

    /**
     * CCN防伪信息查询接口,详情请参见<<中商通用服务接口及数据更新组件设计文档>>
     * 
     * @param mima
     * @param code
     * @param systemState
     * @param getCodeIsTrueOutResult
     * @param ip
     * @param language
     * @param reply
     * @param directoryName
     */
    @WebMethod(operationName = "Get_CodeIsTrueOut", action = "http://fw.yesno.com.cn/CCNCommonService/Get_CodeIsTrueOut")
    @RequestWrapper(localName = "Get_CodeIsTrueOut", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", className = "com.shentian.client.GetCodeIsTrueOut")
    @ResponseWrapper(localName = "Get_CodeIsTrueOutResponse", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", className = "com.shentian.client.GetCodeIsTrueOutResponse")
    public void getCodeIsTrueOut(
        @WebParam(name = "directoryName", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String directoryName,
        @WebParam(name = "mima", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String mima,
        @WebParam(name = "code", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String code,
        @WebParam(name = "ip", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String ip,
        @WebParam(name = "language", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        int language,
        @WebParam(name = "Get_CodeIsTrueOutResult", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<Boolean> getCodeIsTrueOutResult,
        @WebParam(name = "reply", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<String> reply,
        @WebParam(name = "systemState", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<String> systemState);

    /**
     * CCN防伪信息查询接口,详情请参见<<中商通用服务接口及数据更新组件设计文档>>
     * 
     * @param image
     * @param mima
     * @param code
     * @param getCodeIsTrueSpaldingResult
     * @param systemState
     * @param ip
     * @param language
     * @param reply
     * @param directoryName
     */
    @WebMethod(operationName = "Get_CodeIsTrueSpalding", action = "http://fw.yesno.com.cn/CCNCommonService/Get_CodeIsTrueSpalding")
    @RequestWrapper(localName = "Get_CodeIsTrueSpalding", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", className = "com.shentian.client.GetCodeIsTrueSpalding")
    @ResponseWrapper(localName = "Get_CodeIsTrueSpaldingResponse", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", className = "com.shentian.client.GetCodeIsTrueSpaldingResponse")
    public void getCodeIsTrueSpalding(
        @WebParam(name = "directoryName", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String directoryName,
        @WebParam(name = "mima", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String mima,
        @WebParam(name = "code", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String code,
        @WebParam(name = "ip", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String ip,
        @WebParam(name = "language", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        int language,
        @WebParam(name = "Get_CodeIsTrueSpaldingResult", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<Boolean> getCodeIsTrueSpaldingResult,
        @WebParam(name = "reply", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<String> reply,
        @WebParam(name = "systemState", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<String> systemState,
        @WebParam(name = "image", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<String> image);

    /**
     * CCN防伪信息查询接口,详情请参见<<中商通用服务接口及数据更新组件设计文档>>
     * 
     * @param mima
     * @param code
     * @param systemState
     * @param ip
     * @param getCodeIsTrueOutLifeResult
     * @param language
     * @param reply
     * @param directoryName
     */
    @WebMethod(operationName = "Get_CodeIsTrueOutLife", action = "http://fw.yesno.com.cn/CCNCommonService/Get_CodeIsTrueOutLife")
    @RequestWrapper(localName = "Get_CodeIsTrueOutLife", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", className = "com.shentian.client.GetCodeIsTrueOutLife")
    @ResponseWrapper(localName = "Get_CodeIsTrueOutLifeResponse", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", className = "com.shentian.client.GetCodeIsTrueOutLifeResponse")
    public void getCodeIsTrueOutLife(
        @WebParam(name = "directoryName", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String directoryName,
        @WebParam(name = "mima", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String mima,
        @WebParam(name = "code", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String code,
        @WebParam(name = "ip", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String ip,
        @WebParam(name = "language", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        int language,
        @WebParam(name = "Get_CodeIsTrueOutLifeResult", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<Boolean> getCodeIsTrueOutLifeResult,
        @WebParam(name = "reply", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<String> reply,
        @WebParam(name = "systemState", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<String> systemState);

    /**
     * CCN防伪信息查询接口,详情请参见<<中商通用服务接口及数据更新组件设计文档>>
     * 
     * @param mima
     * @param code
     * @param systemState
     * @param ip
     * @param channel
     * @param language
     * @param getCodeIsTrueByChannelResult
     * @param reply
     * @param directoryName
     */
    @WebMethod(operationName = "Get_CodeIsTrueByChannel", action = "http://fw.yesno.com.cn/CCNCommonService/Get_CodeIsTrueByChannel")
    @RequestWrapper(localName = "Get_CodeIsTrueByChannel", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", className = "com.shentian.client.GetCodeIsTrueByChannel")
    @ResponseWrapper(localName = "Get_CodeIsTrueByChannelResponse", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", className = "com.shentian.client.GetCodeIsTrueByChannelResponse")
    public void getCodeIsTrueByChannel(
        @WebParam(name = "directoryName", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String directoryName,
        @WebParam(name = "mima", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String mima,
        @WebParam(name = "code", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String code,
        @WebParam(name = "ip", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String ip,
        @WebParam(name = "language", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        int language,
        @WebParam(name = "channel", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String channel,
        @WebParam(name = "Get_CodeIsTrueByChannelResult", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<Boolean> getCodeIsTrueByChannelResult,
        @WebParam(name = "reply", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<String> reply,
        @WebParam(name = "systemState", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<String> systemState);

    /**
     * CCN防伪信息查询接口,详情请参见<<中商通用服务接口及数据更新组件设计文档>>
     * 
     * @param mima
     * @param code
     * @param systemState
     * @param ip
     * @param language
     * @param reply
     * @param getCodeIsTrueOutLifeByQPResult
     * @param directoryName
     */
    @WebMethod(operationName = "Get_CodeIsTrueOutLifeByQP", action = "http://fw.yesno.com.cn/CCNCommonService/Get_CodeIsTrueOutLifeByQP")
    @RequestWrapper(localName = "Get_CodeIsTrueOutLifeByQP", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", className = "com.shentian.client.GetCodeIsTrueOutLifeByQP")
    @ResponseWrapper(localName = "Get_CodeIsTrueOutLifeByQPResponse", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", className = "com.shentian.client.GetCodeIsTrueOutLifeByQPResponse")
    public void getCodeIsTrueOutLifeByQP(
        @WebParam(name = "directoryName", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String directoryName,
        @WebParam(name = "mima", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String mima,
        @WebParam(name = "code", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String code,
        @WebParam(name = "ip", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        String ip,
        @WebParam(name = "language", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService")
        int language,
        @WebParam(name = "Get_CodeIsTrueOutLifeByQPResult", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<Boolean> getCodeIsTrueOutLifeByQPResult,
        @WebParam(name = "reply", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<String> reply,
        @WebParam(name = "systemState", targetNamespace = "http://fw.yesno.com.cn/CCNCommonService", mode = WebParam.Mode.OUT)
        Holder<String> systemState);

}
